### ISSUE TITLE
HelloWorld fails to run

### ISSUE THREAD

**Issue by Gavin-Williams** [amerkoleci/Vortice.Graphics#1]
#### Description

When i run HelloWorld I get the following errors...

CS8983	A 'struct' with field initializers must include an explicitly declared constructor.	Vortice.Graphics (net6.0), Vortice.Graphics (netstandard2.0)	C:\Users\deads\Desktop\Reference Code\Vortice.Graphics-main\src\Vortice.Graphics\GPUDeviceDescriptor.cs	9	Active

CS0006	Metadata file 'C:\Users\deads\Desktop\Reference Code\Vortice.Graphics-main\src\Vortice.Graphics\obj\Debug\net6.0\ref\Vortice.Graphics.dll' could not be found	Vortice.Graphics.Samples (netstandard2.0)	C:\Users\deads\Desktop\Reference Code\Vortice.Graphics-main\samples\Vortice.Graphics.Samples\CSC	1	Active

CS0006	Metadata file 'C:\Users\deads\Desktop\Reference Code\Vortice.Graphics-main\src\Vortice.Graphics\bin\Debug\netstandard2.0\Vortice.Graphics.dll' could not be found	Vortice.Graphics.Samples (netstandard2.0)	C:\Users\deads\Desktop\Reference Code\Vortice.Graphics-main\samples\Vortice.Graphics.Samples\CSC	1	Active

CS0006	Metadata file 'C:\Users\deads\Desktop\Reference Code\Vortice.Graphics-main\src\Vortice.Graphics\obj\Debug\net6.0\ref\Vortice.Graphics.dll' could not be found	HelloWorld (net6.0)	C:\Users\deads\Desktop\Reference Code\Vortice.Graphics-main\samples\HelloWorld\CSC	1	Active

CS0006	Metadata file 'C:\Users\deads\Desktop\Reference Code\Vortice.Graphics-main\samples\Vortice.Graphics.Samples\obj\Debug\net6.0-windows\ref\Vortice.Graphics.Samples.dll' could not be found	HelloWorld (net6.0)	C:\Users\deads\Desktop\Reference Code\Vortice.Graphics-main\samples\HelloWorld\CSC	1	Active

CS0006	Metadata file 'C:\Users\deads\Desktop\Reference Code\Vortice.Graphics-main\samples\Vortice.Graphics.Samples\obj\Debug\net6.0\ref\Vortice.Graphics.Samples.dll' could not be found	HelloWorld (net6.0)	C:\Users\deads\Desktop\Reference Code\Vortice.Graphics-main\samples\HelloWorld\CSC	1	Active

#### Reproduction Steps

* Using download from github, open HellowWorld project in VS2022
* run

**Comment by amerkoleci** [comment]
Thias has been fixed now!
